version: "3.8"
services:
  mysql:
    image: "mysql:latest"
    restart: on-failure
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: filecrud
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: admin

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      spring.datasource.mysql.jdbcUrl : jdbc:mysql://mysql/filecrud?createDatabaseIfNotExists=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      spring.datasource.mysql.username : username
      spring.datasource.mysql.password : password
    depends_on:
      - mysql